[package]
name = "bitfield-impl"
version = "0.0.0"
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.29"
quote = "1.0.9"
syn = { version = "1.0.77", features = ["full", "extra-traits", "visit-mut"] }
# TODO
